server:
  port: 8087

spring:
  shiro:
    realm-class: quick.pager.shiro.boot.simple.shiro.UserRealm
    login-url: '/admin/login/page'
    success-url: '/admin/login/success'
    filter-chain-definition-map: {'[/admin/login/page]':'anon','[/admin/login]':'anon','[/admin/logout]':'anon','[/admin/**]':'authc'}
    unauthorized-url: '/404'
  freemarker:
    request-context-attribute: request