server:
  port: 8087

spring:
  shiro:
    realm-class: quick.pager.shiro.boot.simple.shiro.UserRealm
    login-url: '/admin/login'
    success-url: '/admin/success'
    unauthorized-url: '/admin/404'
    filter-chain-definition-map: {'[/admin/login/page]':'anon','[/admin/login]':'anon','[/admin/logout]':'anon','[/admin/role/**]':'authc,roles[sp]','[/admin/**]':'authc,roles[admin]'}
    proxy-target-class: true
  freemarker:
    request-context-attribute: request