server:
  port: 8087

spring:
  shiro:
    realm-class: quick.pager.shiro.boot.simple.shiro.UserRealm
    login-url: ''
    success-url: ''
    unauthorized-url: '/admin/404'
    filter-chain-definition-map: {'[/admin/login/page]':'anon','[/admin/login]':'anon,testFilter','[/admin/logout]':'anon','[/admin/role/**]':'authc,roles[sp]','[/admin/**]':'authc,roles[admin]'}
    proxy-target-class: true
    filters: {'testFilter': 'quick.pager.shiro.boot.simple.filter.TestFilter'}
  freemarker:
    request-context-attribute: request